version: '3'
services:
  datascience-notebook:
    build: .
    container_name: jupyter_notebook
    environment:
      - JUPYTER_TOKEN=easy
    volumes:
      - .:/home/jovyan
    ports:
      - 8888:8888
    networks:
      - internal

networks:
  internal:
    driver: bridge